@Library('mylibrary1')_
pipeline
{
    agent any
    stages
    {
        stage('ContDownload_master')
        {
            steps
            {
                script
                {
                cicd1.download("maven")
                }
            }
        }
        stage('ContBuild_master')
        {
            steps
            {
                script
                {
                cicd1.build()
                }
            }
        }
    }
}
